spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}
      database: 0
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

logging:
  level:
    org.fellow99.tpl.appapi: DEBUG

captcha:
  enable: false
